name: Check Image Sizes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.gif'
      - '**/*.webp'

jobs:
  check-image-sizes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69e # v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install image-size

      - name: Run image check script
        run: node public/scripts/workflow/check-images.js

permissions:
  contents: read
  pull-requests: read 