name: Publish Packages

on:
  push:
    branches:
      - master
      - publish_workflow

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: '20'


      - name: Install dependencies, build and publish marketing-scripts
        working-directory: public/scripts/marketing-scripts
        run: |
          npm install
          npm run build
          npx semantic-release

      - name: Install dependencies, build and publish cs-scripts
        working-directory: public/scripts/cs-scripts
        run: |
          npm install
          npm run build
          npx semantic-release


