name: Publish Packages

on:
  push:
    branches:
      - master
      - publish_workflow

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Node.js
        uses: actions/setup-node@3e9b95f53d189266c2d3828f91d3a4477ab163d3
        with:
          node-version: '20'


      - name: Check changes in marketing-scripts
        id: marketing-changes
        run: |
          if git diff --quiet HEAD^ HEAD -- public/scripts/marketing-scripts/src/; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi
        continue-on-error: true 


      - name: Check changes in cs-scripts
        id: cs-changes
        run: |
          if git diff --quiet HEAD^ HEAD -- public/scripts/cs-scripts/src/; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi
        continue-on-error: true 

     
      - name: Install dependencies and build marketing-scripts
        if: ${{ env.changed == 'true' && steps.marketing-changes.outputs.changed == 'true' }}
        working-directory: public/scripts/marketing-scripts
        run: |
          npm install
          npm run build
          npx semantic-release

   
      - name: Install dependencies and build cs-scripts
        if: ${{ env.changed == 'true' && steps.cs-changes.outputs.changed == 'true' }}
        working-directory: public/scripts/cs-scripts
        run: |
          npm install
          npm run build
          npx semantic-release
