name: Notify Slack on Merge Request

on:
  issue_comment:
    types: [created]

jobs:
  notify-slack:
    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, '@request_merge')
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_URL: ${{ github.event.issue.html_url }}
          COMMENTER: ${{ github.event.comment.user.login }}
        run: |
          read -r -d '' payload <<EOF
          {
            "text": "<@UDJT9F43E> Amam\n\n<@U01TJKCS09K> Prince\n\n<@U01P4V6M2GK> habib\n\n<@U04LLQ3GBB5> nuzhy\n\n:bell: Merge Requested\nA merge has been requested by @${COMMENTER}.\nPR: ${PR_URL}"
          }
          EOF
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"